#
# fml_generate_registry - 生成模块注册表
#
# 生成一个包含所有注册模块的 C++ 文件
#
function(fml_generate_registry OUTPUT_FILE)
    # 获取所有模块
    get_property(modules GLOBAL PROPERTY FML_MODULE_LIST)

    list(LENGTH modules module_count)
    message(STATUS "Generating module registry: ${module_count} modules")

    if(NOT modules)
        message(WARNING "No modules registered, generating empty registry")
        set(modules "")
    endif()

    # 生成代码
    set(REGISTRY_CODE "/*\n")
    set(REGISTRY_CODE "${REGISTRY_CODE} * Auto-generated by fml_generate_registry\n")
    set(REGISTRY_CODE "${REGISTRY_CODE} * DO NOT EDIT!\n")
    set(REGISTRY_CODE "${REGISTRY_CODE} */\n\n")
    string(APPEND REGISTRY_CODE "#include <string.h>\n")

    # 平台特定的头文件
    if(DEFINED ENV{ZEPHYR_BASE})
        string(APPEND REGISTRY_CODE "#include <zephyr/kernel.h>\n")
    else()
        string(APPEND REGISTRY_CODE "#include <cstdio>\n")
    endif()
    string(APPEND REGISTRY_CODE "\n")

    # 声明 extern 函数
    foreach(module ${modules})
        string(APPEND REGISTRY_CODE "extern \"C\" int ${module}_main(int argc, char *argv[]);\n")
    endforeach()

    # 定义结构体
    string(APPEND REGISTRY_CODE "\nstruct builtin_command_t {\n")
    string(APPEND REGISTRY_CODE "    const char *name;\n")
    string(APPEND REGISTRY_CODE "    int (*main)(int argc, char *argv[]);\n")
    string(APPEND REGISTRY_CODE "};\n\n")

    # 生成数组
    string(APPEND REGISTRY_CODE "static const builtin_command_t builtins[] = {\n")
    foreach(module ${modules})
        string(APPEND REGISTRY_CODE "    {\"${module}\", ${module}_main},\n")
    endforeach()
    string(APPEND REGISTRY_CODE "};\n\n")

    string(APPEND REGISTRY_CODE "static const int builtin_count = sizeof(builtins) / sizeof(builtins[0]);\n\n")

    # 添加查找和执行函数
    string(APPEND REGISTRY_CODE "
extern \"C\" int builtin_command_execute(const char *name, int argc, char *argv[])
{
    for (int i = 0; i < builtin_count; i++) {
        if (strcmp(name, builtins[i].name) == 0) {
            return builtins[i].main(argc, argv);
        }
    }
    return -1;
}

extern \"C\" void builtin_command_list(void)
{
#ifdef FML_ZEPHYR
    printk(\"Available commands: (%d)\\n\", builtin_count);
    for (int i = 0; i < builtin_count; i++) {
        printk(\"  %s\\n\", builtins[i].name);
    }
#else
    printf(\"Available commands: (%d)\\n\", builtin_count);
    for (int i = 0; i < builtin_count; i++) {
        printf(\"  %s\\n\", builtins[i].name);
    }
#endif
}

extern \"C\" int builtin_command_count(void)
{
    return builtin_count;
}

extern \"C\" const char* builtin_command_get_name(int index)
{
    if (index >= 0 && index < builtin_count) {
        return builtins[index].name;
    }
    return NULL;
}
")

    # 写入文件
    file(WRITE ${OUTPUT_FILE} "${REGISTRY_CODE}")
    message(STATUS "  Generated: ${OUTPUT_FILE}")

    # 打印注册的模块列表
    foreach(module ${modules})
        message(STATUS "    - ${module}")
    endforeach()
endfunction()
